/* 2025 샘플 세션 (테스트용 mock 데이터).
 * 실제 2026 카탈로그가 들어오면 삭제할 것. 삭제 시 함께 제거:
 *  1. 이 파일 (js/mock_sessions.js)
 *  2. index.html의 <script src="js/mock_sessions.js"> 태그
 *  3. sw.js ASSETS의 "./js/mock_sessions.js" 항목
 *  4. 홈 설정의 "2025 샘플 세션" 토글 버튼 (Settings.toggleMock)
 *  5. app.js의 allSessions()/sessionsPending() 내 mock 분기
 * 날짜는 앱의 행사 기간(2026-11-30~12-04)에 맞춰 두어 플래너·검색·관심 기능을 그대로 테스트할 수 있다.
 */
"use strict";

/* 전역(window)에 올리기 위해 var 사용 — app.js의 window.MOCK_SESSIONS_2025 체크와 매칭 */
var MOCK_SESSIONS_2025 = [
  { session_id: "MOCK-KEY01", code: "KEY01", title: "[2025 샘플] CEO 키노트: 다음 10년의 클라우드", abstract: "2025년 키노트 스타일 샘플 세션입니다.", session_type: "keynote", session_format: "lecture", level: "", topics: ["기조연설"], services: [], date: "2026-12-01", start_time: "09:00", end_time: "11:00", timezone: "America/Los_Angeles", venue: "The Venetian", room: "The Venetian | Hall", speakers: ["AWS CEO"], delivery: "in-person", mock: true },
  { session_id: "MOCK-ANT201", code: "ANT201", title: "[2025 샘플] Amazon Nova 파운데이션 모델 시작하기", abstract: "Nova 모델 활용법 샘플.", session_type: "breakout", session_format: "lecture", level: "200", topics: ["인공지능"], services: ["Amazon Bedrock"], date: "2026-11-30", start_time: "10:00", end_time: "11:00", timezone: "America/Los_Angeles", venue: "Caesars Forum", room: "Caesars Forum | 101", speakers: ["김노바"], delivery: "in-person", mock: true },
  { session_id: "MOCK-ANT202", code: "ANT202", title: "[2025 샘플] Bedrock 에이전트로 업무 자동화하기", abstract: "", session_type: "chalk-talk", session_format: "discussion", level: "300", topics: ["인공지능"], services: ["Amazon Bedrock"], date: "2026-11-30", start_time: "13:00", end_time: "14:00", timezone: "America/Los_Angeles", venue: "MGM Grand", room: "MGM Grand | 201", speakers: ["이에이전트"], delivery: "in-person", mock: true },
  { session_id: "MOCK-DAT301", code: "DAT301", title: "[2025 샘플] Aurora DSQL: 분산 SQL의 모든 것", abstract: "", session_type: "breakout", session_format: "lecture", level: "300", topics: ["데이터베이스"], services: ["Amazon Aurora"], date: "2026-12-01", start_time: "14:00", end_time: "15:00", timezone: "America/Los_Angeles", venue: "The Venetian", room: "The Venetian | 302", speakers: ["박디비"], delivery: "in-person", mock: true },
  { session_id: "MOCK-DAT302", code: "DAT302", title: "[2025 샘플] S3 Tables로 데이터 레이크 정복", abstract: "", session_type: "workshop", session_format: "hands-on", level: "300", topics: ["스토리지"], services: ["Amazon S3"], date: "2026-12-02", start_time: "09:00", end_time: "11:00", timezone: "America/Los_Angeles", venue: "Caesars Forum", room: "Caesars Forum | Lab 1", speakers: ["최스토리지"], delivery: "in-person", mock: true },
  { session_id: "MOCK-CMP401", code: "CMP401", title: "[2025 샘플] Graviton4로 비용 40% 줄이기", abstract: "", session_type: "breakout", session_format: "lecture", level: "400", topics: ["컴퓨팅"], services: ["Amazon EC2"], date: "2026-12-01", start_time: "16:00", end_time: "17:00", timezone: "America/Los_Angeles", venue: "Wynn", room: "Wynn | 401", speakers: ["정그레비톤"], delivery: "in-person", mock: true },
  { session_id: "MOCK-AIM402", code: "AIM402", title: "[2025 샘플] Trainium2 대규모 학습 실전", abstract: "", session_type: "workshop", session_format: "hands-on", level: "400", topics: ["인공지능"], services: ["Amazon SageMaker"], date: "2026-12-02", start_time: "14:00", end_time: "16:00", timezone: "America/Los_Angeles", venue: "MGM Grand", room: "MGM Grand | Lab 2", speakers: ["한트레이니움"], delivery: "in-person", mock: true },
  { session_id: "MOCK-SEC201", code: "SEC201", title: "[2025 샘플] IAM Access Analyzer 완전 정복", abstract: "", session_type: "chalk-talk", session_format: "discussion", level: "200", topics: ["보안"], services: ["AWS IAM"], date: "2026-12-03", start_time: "10:00", end_time: "11:00", timezone: "America/Los_Angeles", venue: "Caesars Palace", room: "Caesars Palace | 102", speakers: ["강시큐리티"], delivery: "in-person", mock: true },
  { session_id: "MOCK-SEC301", code: "SEC301", title: "[2025 샘플] 제로 트러스트 아키텍처 구축기", abstract: "", session_type: "breakout", session_format: "lecture", level: "300", topics: ["보안"], services: [], date: "2026-12-03", start_time: "13:00", end_time: "14:00", timezone: "America/Los_Angeles", venue: "Caesars Palace", room: "Caesars Palace | 103", speakers: ["윤제로"], delivery: "in-person", mock: true },
  { session_id: "MOCK-SVR202", code: "SVR202", title: "[2025 샘플] Lambda SnapStart 콜드스타트 잡기", abstract: "", session_type: "breakout", session_format: "lecture", level: "200", topics: ["서버리스"], services: ["AWS Lambda"], date: "2026-11-30", start_time: "16:00", end_time: "17:00", timezone: "America/Los_Angeles", venue: "Encore", room: "Encore | 202", speakers: ["서버리스킴"], delivery: "in-person", mock: true },
  { session_id: "MOCK-CON301", code: "CON301", title: "[2025 샘플] EKS Auto Mode 운영 노하우", abstract: "", session_type: "chalk-talk", session_format: "discussion", level: "300", topics: ["컨테이너"], services: ["Amazon EKS"], date: "2026-12-02", start_time: "11:00", end_time: "12:00", timezone: "America/Los_Angeles", venue: "The Venetian", room: "The Venetian | 303", speakers: ["컨테이너박"], delivery: "in-person", mock: true },
  { session_id: "MOCK-NET201", code: "NET201", title: "[2025 샘플] Cloud WAN 글로벌 네트워크 설계", abstract: "", session_type: "breakout", session_format: "lecture", level: "200", topics: ["네트워킹"], services: ["AWS Cloud WAN"], date: "2026-12-04", start_time: "10:00", end_time: "11:00", timezone: "America/Los_Angeles", venue: "Caesars Forum", room: "Caesars Forum | 104", speakers: ["나넷웍"], delivery: "in-person", mock: true },
  { session_id: "MOCK-OPS302", code: "OPS302", title: "[2025 샘플] CloudWatch로 옵저버빌리티 완성", abstract: "", session_type: "workshop", session_format: "hands-on", level: "300", topics: ["운영"], services: ["Amazon CloudWatch"], date: "2026-12-04", start_time: "13:00", end_time: "15:00", timezone: "America/Los_Angeles", venue: "MGM Grand", room: "MGM Grand | Lab 3", speakers: ["옵저버김"], delivery: "in-person", mock: true },
  { session_id: "MOCK-STG201", code: "STG201", title: "[2025 샘플] 마이그레이션 7R 전략", abstract: "", session_type: "breakout", session_format: "lecture", level: "200", topics: ["마이그레이션"], services: [], date: "2026-11-30", start_time: "11:00", end_time: "12:00", timezone: "America/Los_Angeles", venue: "Wynn", room: "Wynn | 201", speakers: ["마이사"], delivery: "in-person", mock: true },
  { session_id: "MOCK-AIM201", code: "AIM201", title: "[2025 샘플] Q Developer로 개발 생산성 2배", abstract: "", session_type: "chalk-talk", session_format: "discussion", level: "200", topics: ["인공지능"], services: ["Amazon Q"], date: "2026-12-01", start_time: "11:00", end_time: "12:00", timezone: "America/Los_Angeles", venue: "Encore", room: "Encore | 203", speakers: ["큐개발자"], delivery: "in-person", mock: true },
  { session_id: "MOCK-DOP301", code: "DOP301", title: "[2025 샘플] GitOps 파이프라인 with CodePipeline", abstract: "", session_type: "breakout", session_format: "lecture", level: "300", topics: ["데브옵스"], services: [], date: "2026-12-03", start_time: "15:00", end_time: "16:00", timezone: "America/Los_Angeles", venue: "The Venetian", room: "The Venetian | 304", speakers: ["데브옵스이"], delivery: "in-person", mock: true },
  { session_id: "MOCK-GAME01", code: "GAME01", title: "[2025 샘플] GameDay: 장애 주입 서바이벌", abstract: "", session_type: "game-day", session_format: "hands-on", level: "300", topics: ["운영"], services: [], date: "2026-12-02", start_time: "16:00", end_time: "18:00", timezone: "America/Los_Angeles", venue: "Caesars Forum", room: "Caesars Forum | Arena", speakers: [], delivery: "in-person", mock: true },
  { session_id: "MOCK-KEY02", code: "KEY02", title: "[2025 샘플] CTO 키노트: 아키텍처의 미래", abstract: "", session_type: "keynote", session_format: "lecture", level: "", topics: ["기조연설"], services: [], date: "2026-12-02", start_time: "09:00", end_time: "10:30", timezone: "America/Los_Angeles", venue: "The Venetian", room: "The Venetian | Hall", speakers: ["AWS CTO"], delivery: "in-person", mock: true },
  { session_id: "MOCK-IOT201", code: "IOT201", title: "[2025 샘플] IoT Core 대규모 디바이스 관리", abstract: "", session_type: "breakout", session_format: "lecture", level: "200", topics: ["IoT"], services: ["AWS IoT Core"], date: "2026-12-04", start_time: "15:00", end_time: "16:00", timezone: "America/Los_Angeles", venue: "Encore", room: "Encore | 204", speakers: ["아이오티박"], delivery: "in-person", mock: true },
  { session_id: "MOCK-ANA301", code: "ANA301", title: "[2025 샘플] Redshift Serverless 성능 튜닝", abstract: "", session_type: "chalk-talk", session_format: "discussion", level: "300", topics: ["분석"], services: ["Amazon Redshift"], date: "2026-12-01", start_time: "13:00", end_time: "14:00", timezone: "America/Los_Angeles", venue: "MGM Grand", room: "MGM Grand | 202", speakers: ["분석가최"], delivery: "in-person", mock: true },
  { session_id: "MOCK-ARC402", code: "ARC402", title: "[2025 샘플] 멀티 리전 액티브-액티브 설계", abstract: "", session_type: "breakout", session_format: "lecture", level: "400", topics: ["아키텍처"], services: [], date: "2026-12-03", start_time: "11:00", end_time: "12:00", timezone: "America/Los_Angeles", venue: "Wynn", room: "Wynn | 402", speakers: ["아키텍트신"], delivery: "in-person", mock: true },
  { session_id: "MOCK-BIZ101", code: "BIZ101", title: "[2025 샘플] 클라우드 비용 최적화 첫걸음", abstract: "", session_type: "breakout", session_format: "lecture", level: "100", topics: ["비용"], services: [], date: "2026-11-30", start_time: "14:00", end_time: "15:00", timezone: "America/Los_Angeles", venue: "Caesars Palace", room: "Caesars Palace | 101", speakers: ["비용절감왕"], delivery: "in-person", mock: true },
  { session_id: "MOCK-DEV202", code: "DEV202", title: "[2025 샘플] Amplify Gen 2 풀스택 앱 만들기", abstract: "", session_type: "workshop", session_format: "hands-on", level: "200", topics: ["데브옵스"], services: ["AWS Amplify"], date: "2026-12-04", start_time: "09:00", end_time: "11:00", timezone: "America/Los_Angeles", venue: "Caesars Forum", room: "Caesars Forum | Lab 4", speakers: ["풀스택정"], delivery: "in-person", mock: true },
  { session_id: "MOCK-KEY03", code: "KEY03", title: "[2025 샘플] 파트너 키노트", abstract: "", session_type: "keynote", session_format: "lecture", level: "", topics: ["기조연설"], services: [], date: "2026-12-03", start_time: "09:00", end_time: "10:00", timezone: "America/Los_Angeles", venue: "The Venetian", room: "The Venetian | Hall", speakers: [], delivery: "in-person", mock: true }
];
